/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PenjualanController;
import java.awt.Point;
import java.awt.event.KeyEvent;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Irawan
 */
public class FormPenjualan extends javax.swing.JInternalFrame {
    private final DefaultTableModel penjualanDefaultTableModel;
    private final PenjualanController penjualanController=new PenjualanController();

    /**
     * Creates new form FormNilai
     */
    public FormPenjualan() {
        initComponents();
        
        
        penjualanDefaultTableModel=(DefaultTableModel) penjualanTable.getModel();
        setMnemonic();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        penjualanPopupMenu = new javax.swing.JPopupMenu();
        tambahMenuItem = new javax.swing.JMenuItem();
        hapusMenuItem = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        tutupButton = new javax.swing.JButton();
        simpanButton = new javax.swing.JButton();
        lihatButton = new javax.swing.JButton();
        kodeBarangTextField = new javax.swing.JTextField();
        namaLabel = new javax.swing.JLabel();
        nimLabel = new javax.swing.JLabel();
        nomorTextField = new javax.swing.JTextField();
        nilaiPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        penjualanTable = new javax.swing.JTable();
        kelasLabel = new javax.swing.JLabel();
        tanggalTextField = new javax.swing.JTextField();
        namaBarangTextField = new javax.swing.JTextField();
        semesterLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namaCustomerTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        tambahMenuItem.setText("jMenuItem1");
        tambahMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahMenuItemActionPerformed(evt);
            }
        });
        penjualanPopupMenu.add(tambahMenuItem);

        hapusMenuItem.setText("jMenuItem1");
        hapusMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusMenuItemActionPerformed(evt);
            }
        });
        penjualanPopupMenu.add(hapusMenuItem);

        setClosable(true);
        setTitle("Form Penjualan Barang");

        tutupButton.setText("Tutup");
        tutupButton.setNextFocusableComponent(kodeBarangTextField);
        tutupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutupButtonActionPerformed(evt);
            }
        });

        simpanButton.setText("Simpan");
        simpanButton.setNextFocusableComponent(tutupButton);
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        lihatButton.setText("Lihat");
        lihatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatButtonActionPerformed(evt);
            }
        });

        kodeBarangTextField.setName("NIM"); // NOI18N
        kodeBarangTextField.setNextFocusableComponent(lihatButton);
        kodeBarangTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kodeBarangTextFieldKeyPressed(evt);
            }
        });

        namaLabel.setLabelFor(namaBarangTextField);
        namaLabel.setText("Nama Barang");

        nimLabel.setDisplayedMnemonic((int)'N');
        nimLabel.setLabelFor(kodeBarangTextField);
        nimLabel.setText("Kode Barang");
        nimLabel.setNextFocusableComponent(kodeBarangTextField);

        nomorTextField.setEditable(false);

        nilaiPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Penjualan"));

        penjualanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "NamaBarang", "Harga", "Banyaknya", "Satuan", "Jumlah"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        penjualanTable.setNextFocusableComponent(simpanButton);
        penjualanTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        penjualanTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                penjualanTableMouseReleased(evt);
            }
        });
        penjualanTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                penjualanTablePropertyChange(evt);
            }
        });
        penjualanTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                penjualanTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(penjualanTable);

        javax.swing.GroupLayout nilaiPanelLayout = new javax.swing.GroupLayout(nilaiPanel);
        nilaiPanel.setLayout(nilaiPanelLayout);
        nilaiPanelLayout.setHorizontalGroup(
            nilaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );
        nilaiPanelLayout.setVerticalGroup(
            nilaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        kelasLabel.setLabelFor(nomorTextField);
        kelasLabel.setText("No.");

        tanggalTextField.setEditable(false);

        namaBarangTextField.setEditable(false);

        semesterLabel.setLabelFor(tanggalTextField);
        semesterLabel.setText("Tanggal");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setText("jTextField1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Total : Rp");

        jLabel2.setText("Kepada");

        jButton2.setText("Lihat");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(namaLabel)
                            .addComponent(nimLabel)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namaBarangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(kodeBarangTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                    .addComponent(namaCustomerTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(lihatButton))))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kelasLabel)
                            .addComponent(semesterLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tanggalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(simpanButton, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(tutupButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nilaiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(simpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(namaCustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(tanggalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(semesterLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nimLabel)
                            .addComponent(kodeBarangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lihatButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(namaBarangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kelasLabel)
                    .addComponent(nomorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tutupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(nilaiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    	public void setKode(String kode){
        kodeBarangTextField.setText(kode);
    }
        public void setMnemonic(){
            nimLabel.setDisplayedMnemonic('N');
            lihatButton.setMnemonic('I');
            simpanButton.setMnemonic('S');
            tutupButton.setMnemonic('U');
            
        }
    
    public void setNamaBarang(String namaBarang){
        namaBarangTextField.setText(namaBarang);
    }
    
    public void setTanggal(String tanggal){
	tanggalTextField.setText(tanggal);
    }
    
    public void setNomor(String nomor){
	nomorTextField.setText(nomor);
    }
    
    public void setNamaBarangTabel(String namaBarangTabel){
	penjualanTable.setValueAt(namaBarangTabel, penjualanTable.getSelectedRow(), 1);
    }
    
    public void setTambahNilai(Object[] banyaknya){
        int noRecord;
        
        if ((noRecord = penjualanDefaultTableModel.getRowCount()-1) >= 0){
            while ((((penjualanTable.getValueAt(noRecord, 0) == null) || penjualanTable.getValueAt(noRecord, 0).equals("")) && (noRecord > 0))){
                noRecord--;
            }
            
            if (!((penjualanTable.getValueAt(noRecord, 0) == null) || penjualanTable.getValueAt(noRecord, 0).equals(""))){
                noRecord++;
            }
            
            if (noRecord < penjualanDefaultTableModel.getRowCount()){
                if ((penjualanTable.getValueAt(noRecord, 0) == null) || penjualanTable.getValueAt(noRecord, 0).equals("")){
                    penjualanDefaultTableModel.removeRow(noRecord--);
                }
            } else {
                noRecord--;
            }
        }
        
        penjualanDefaultTableModel.insertRow(++noRecord, banyaknya);
    }
    
    public void clearBanyaknyaTable(){
        penjualanDefaultTableModel.setRowCount(0);
    }
    
    private void klikKananTabel(java.awt.event.MouseEvent evt){
        if(evt.isPopupTrigger()){
            penjualanPopupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }

    private void tutupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutupButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_tutupButtonActionPerformed

    private void penjualanTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penjualanTableMouseReleased
        // TODO add your handling code here:
                Point p = evt.getPoint();
        int rowNumber = penjualanTable.rowAtPoint( p );
        ListSelectionModel model = penjualanTable.getSelectionModel();
        model.setSelectionInterval( rowNumber, rowNumber );
        
        klikKananTabel(evt);

    }//GEN-LAST:event_penjualanTableMouseReleased

    private void penjualanTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_penjualanTableKeyPressed
        // TODO add your handling code here:
              if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (penjualanTable.getSelectedRow() == (penjualanTable.getRowCount()-1)){
                if (penjualanTable.getSelectedColumn()==0){
                    penjualanDefaultTableModel.insertRow( penjualanDefaultTableModel.getRowCount(), new Object[]{}); 
                } else {
                    if (penjualanTable.getSelectedColumn() == (penjualanTable.getColumnCount()-1)){
                        penjualanDefaultTableModel.insertRow( penjualanDefaultTableModel.getRowCount(), new Object[]{});
                        penjualanTable.changeSelection(penjualanTable.getSelectedRow(), 0, false, false);
                    } else {
                        penjualanTable.changeSelection(penjualanTable.getSelectedRow()-1, penjualanTable.getSelectedColumn()+1, false, false);                    
                    }
                }
            } else {
                if (penjualanTable.getSelectedColumn() == (penjualanTable.getColumnCount()-1)){
                    penjualanTable.changeSelection(penjualanTable.getSelectedRow(), 0, false, false);
                } else {
                    penjualanTable.setColumnSelectionInterval(penjualanTable.getSelectedColumn()+1,penjualanTable.getSelectedColumn()+1);
                    penjualanTable.setRowSelectionInterval(penjualanTable.getSelectedRow()-1,penjualanTable.getSelectedRow()-1);
                }
            }
        }

    }//GEN-LAST:event_penjualanTableKeyPressed

    private void penjualanTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_penjualanTablePropertyChange
        // TODO add your handling code here:
               if (penjualanTable.getSelectedRowCount()>0){
            if (penjualanTable.getSelectedColumn()==0){
                String kodeBarang = "";
                try{
                    kodeBarang = penjualanTable.getValueAt(penjualanTable.getSelectedRow(), 0).toString();                
		}catch (Exception ex){}
                
		if (!kodeBarang.equals("")){
//                    penjualanController.cariK(kodeBarang); 	            
		}
            }
        }

    }//GEN-LAST:event_penjualanTablePropertyChange

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        // TODO add your handling code here:
  //      penjualanController.simpan(kodeBarangTextField,penjualanTable);
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void lihatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatButtonActionPerformed
        // TODO add your handling code here:
//        penjualanController.tampilkanFormLihatBarang();
    }//GEN-LAST:event_lihatButtonActionPerformed

    private void kodeBarangTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kodeBarangTextFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            penjualanController.cariBarang(kodeBarangTextField);
        }
    }//GEN-LAST:event_kodeBarangTextFieldKeyPressed

    private void tambahMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahMenuItemActionPerformed
        // TODO add your handling code here:
//        penjualanController.tampilkanFormLihatMataKuliah();
    }//GEN-LAST:event_tambahMenuItemActionPerformed

    private void hapusMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusMenuItemActionPerformed
        // TODO add your handling code here:
        if(penjualanTable.getSelectedRowCount()>0){
            penjualanDefaultTableModel.removeRow(penjualanTable.getSelectedRow());
        }
    }//GEN-LAST:event_hapusMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem hapusMenuItem;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel kelasLabel;
    private javax.swing.JTextField kodeBarangTextField;
    private javax.swing.JButton lihatButton;
    private javax.swing.JTextField namaBarangTextField;
    private javax.swing.JTextField namaCustomerTextField;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JPanel nilaiPanel;
    private javax.swing.JLabel nimLabel;
    private javax.swing.JTextField nomorTextField;
    private javax.swing.JPopupMenu penjualanPopupMenu;
    private javax.swing.JTable penjualanTable;
    private javax.swing.JLabel semesterLabel;
    private javax.swing.JButton simpanButton;
    private javax.swing.JMenuItem tambahMenuItem;
    private javax.swing.JTextField tanggalTextField;
    private javax.swing.JButton tutupButton;
    // End of variables declaration//GEN-END:variables
}
